import type { ServiceJob } from '../../types';

const phoneCracked =
  'https://images.pexels.com/photos/288479/pexels-photo-288479.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const phoneBroken2 =
  'https://images.pexels.com/photos/11921157/pexels-photo-11921157.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const laptopDesk =
  'https://images.pexels.com/photos/34804001/pexels-photo-34804001.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const laptopMono =
  'https://images.pexels.com/photos/265144/pexels-photo-265144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const headphonesWhite =
  'https://images.pexels.com/photos/3394666/pexels-photo-3394666.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const headphonesBlack =
  'https://images.pexels.com/photos/815494/pexels-photo-815494.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const watchWrist =
  'https://images.pexels.com/photos/267391/pexels-photo-267391.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const watchOutdoor =
  'https://images.pexels.com/photos/374619/pexels-photo-374619.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';

export const mockServiceJobs: ServiceJob[] = [
  {
    id: 'SRV-2026-0481',
    brandId: 'bruno-thailand',
    publicTrackingTokenHash: null,
    publicTrackingCodeHash: null,
    customerName: 'Margaret Chen',
    customerPhone: '(415) 555-0182',
    customerEmail: 'margaret.chen@gmail.com',
    product: 'iPhone 15 Pro Max',
    productCategory: 'Smartphone',
    serialNumber: 'F2LX9PM3KQH7',
    issue: 'Cracked screen',
    description:
      'Dropped on tile floor. Display still responds to touch but glass is shattered across the lower third. No liquid damage.',
    status: 'In Repair',
    priority: 'Normal',
    createdAt: '2026-08-02',
    updatedAt: '2026-08-05',
    closedAt: null,
    technician: 'Daniel Okafor',
    estimatedCompletion: '2026-08-08',
    warranty: false,
    photos: [phoneCracked, phoneBroken2],
    quote: 329,
    timeline: [
      {
        status: 'Received',
        title: 'Claim received',
        description: 'Device dropped off at the Powell Street service counter.',
        date: '2026-08-02',
        time: '10:24 AM',
        done: true,
      },
      {
        status: 'Diagnosing',
        title: 'Diagnosis complete',
        description: 'Front display assembly needs replacement. Battery health at 91%.',
        date: '2026-08-03',
        time: '2:10 PM',
        done: true,
      },
      {
        status: 'Awaiting Parts',
        title: 'Parts ordered',
        description: 'OLED display assembly on order from regional warehouse.',
        date: '2026-08-03',
        time: '4:48 PM',
        done: true,
      },
      {
        status: 'In Repair',
        title: 'Repair in progress',
        description: 'Display assembly being fitted and calibrated by technician.',
        date: '2026-08-05',
        time: '9:30 AM',
        done: true,
        current: true,
      },
      {
        status: 'Quality Check',
        title: 'Quality check',
        description: 'Final function and water-resistance test pending.',
        date: '—',
        time: '',
        done: false,
      },
      {
        status: 'Ready for Pickup',
        title: 'Ready for pickup',
        description: 'We will text and email you when the device is ready.',
        date: '—',
        time: '',
        done: false,
      },
    ],
    notes: [
      {
        author: 'Daniel Okafor',
        date: '2026-08-03',
        text: 'Customer asked to preserve screen protector if possible — not salvageable, will include a replacement at no charge.',
      },
    ],
  },
  {
    id: 'SRV-2026-0479',
    brandId: 'bruno-thailand',
    publicTrackingTokenHash: null,
    publicTrackingCodeHash: null,
    customerName: 'Robert Hayes',
    customerPhone: '(415) 555-0144',
    customerEmail: 'r.hayes@outlook.com',
    product: 'MacBook Air M3 13"',
    productCategory: 'Laptop',
    serialNumber: 'C02XK1PQLVDQ',
    issue: 'Won’t turn on',
    description:
      'No response after being left in a car on a hot day. MagSafe light flickers briefly then dies.',
    status: 'Diagnosing',
    priority: 'High',
    createdAt: '2026-08-04',
    updatedAt: '2026-08-05',
    closedAt: null,
    technician: 'Priya Nair',
    estimatedCompletion: '2026-08-09',
    warranty: true,
    photos: [laptopDesk, laptopMono],
    quote: 0,
    timeline: [
      {
        status: 'Received',
        title: 'Claim received',
        description: 'Drop-off at front counter. Warranty verified through AppleCare+.',
        date: '2026-08-04',
        time: '11:02 AM',
        done: true,
      },
      {
        status: 'Diagnosing',
        title: 'Diagnosis in progress',
        description: 'Logic board and battery under thermal inspection.',
        date: '2026-08-05',
        time: '8:45 AM',
        done: true,
        current: true,
      },
      {
        status: 'Awaiting Parts',
        title: 'Awaiting parts',
        description: 'Pending diagnosis outcome.',
        date: '—',
        time: '',
        done: false,
      },
      {
        status: 'In Repair',
        title: 'In repair',
        description: 'Repair work will begin once parts arrive.',
        date: '—',
        time: '',
        done: false,
      },
      {
        status: 'Ready for Pickup',
        title: 'Ready for pickup',
        description: 'We will notify you when the repair is complete.',
        date: '—',
        time: '',
        done: false,
      },
    ],
    notes: [
      {
        author: 'Priya Nair',
        date: '2026-08-05',
        text: 'Possible thermal shutdown protection tripped. Running extended diagnostics before opening chassis.',
      },
    ],
  },
  {
    id: 'SRV-2026-0477',
    brandId: 'bruno-thailand',
    publicTrackingTokenHash: null,
    publicTrackingCodeHash: null,
    customerName: 'Linda Park',
    customerPhone: '(415) 555-0119',
    customerEmail: 'lindapark@icloud.com',
    product: 'AirPods Pro 2',
    productCategory: 'Headphones',
    serialNumber: 'AP2-7741-2930',
    issue: 'Left earbud no audio',
    description:
      'Right earbud works normally. Left produces static then cuts out after 30 seconds.',
    status: 'Ready for Pickup',
    priority: 'Normal',
    createdAt: '2026-07-29',
    updatedAt: '2026-08-05',
    closedAt: null,
    technician: 'Daniel Okafor',
    estimatedCompletion: '2026-08-05',
    warranty: true,
    photos: [headphonesWhite, headphonesBlack],
    quote: 0,
    timeline: [
      {
        status: 'Received',
        title: 'Claim received',
        description: 'Brought in for audio fault on left earbud.',
        date: '2026-07-29',
        time: '3:15 PM',
        done: true,
      },
      {
        status: 'Diagnosing',
        title: 'Diagnosis complete',
        description: 'Driver fault confirmed. Replaced under AppleCare+.',
        date: '2026-07-30',
        time: '10:40 AM',
        done: true,
      },
      {
        status: 'In Repair',
        title: 'Repaired',
        description: 'Left earbud replaced and paired to case.',
        date: '2026-08-01',
        time: '1:20 PM',
        done: true,
      },
      {
        status: 'Quality Check',
        title: 'Passed quality check',
        description: 'Audio, ANC, and charging all verified.',
        date: '2026-08-02',
        time: '9:00 AM',
        done: true,
      },
      {
        status: 'Ready for Pickup',
        title: 'Ready for pickup',
        description: 'Available at the counter during business hours.',
        date: '2026-08-05',
        time: '10:00 AM',
        done: true,
        current: true,
      },
    ],
    notes: [],
  },
  {
    id: 'SRV-2026-0475',
    brandId: 'bruno-thailand',
    publicTrackingTokenHash: null,
    publicTrackingCodeHash: null,
    customerName: 'James Whitfield',
    customerPhone: '(415) 555-0173',
    customerEmail: 'jwhitfield@gmail.com',
    product: 'Apple Watch Series 10',
    productCategory: 'Smartwatch',
    serialNumber: 'AW10-5519-8842',
    issue: 'Battery draining fast',
    description: 'Battery drops from 80% to 0% in under three hours with light use.',
    status: 'Quality Check',
    priority: 'Normal',
    createdAt: '2026-08-01',
    updatedAt: '2026-08-06',
    closedAt: null,
    technician: 'Priya Nair',
    estimatedCompletion: '2026-08-06',
    warranty: false,
    photos: [watchWrist, watchOutdoor],
    quote: 129,
    timeline: [
      {
        status: 'Received',
        title: 'Claim received',
        description: 'Watch dropped off for battery service.',
        date: '2026-08-01',
        time: '12:10 PM',
        done: true,
      },
      {
        status: 'Diagnosing',
        title: 'Diagnosis complete',
        description: 'Battery cell degraded to 71% capacity.',
        date: '2026-08-02',
        time: '11:30 AM',
        done: true,
      },
      {
        status: 'In Repair',
        title: 'Battery replaced',
        description: 'Genuine battery installed and sealed.',
        date: '2026-08-04',
        time: '2:00 PM',
        done: true,
      },
      {
        status: 'Quality Check',
        title: 'Quality check in progress',
        description: 'Water-resistance and sensor calibration underway.',
        date: '2026-08-06',
        time: '9:15 AM',
        done: true,
        current: true,
      },
      {
        status: 'Ready for Pickup',
        title: 'Ready for pickup',
        description: 'Final step before pickup notification.',
        date: '—',
        time: '',
        done: false,
      },
    ],
    notes: [
      {
        author: 'Priya Nair',
        date: '2026-08-04',
        text: 'New battery seated. Running 24-hour drain test before closing claim.',
      },
    ],
  },
  {
    id: 'SRV-2026-0472',
    brandId: 'bruno-thailand',
    publicTrackingTokenHash: null,
    publicTrackingCodeHash: null,
    customerName: 'Sofia Rinaldi',
    customerPhone: '(415) 555-0166',
    customerEmail: 'sofia.rinaldi@gmail.com',
    product: 'iPad Air 11"',
    productCategory: 'Tablet',
    serialNumber: 'DMPXQ9L2NHYT',
    issue: 'Charging port loose',
    description: 'Cable falls out of the port and only charges at a specific angle.',
    status: 'Received',
    priority: 'Low',
    createdAt: '2026-08-06',
    updatedAt: '2026-08-06',
    closedAt: null,
    technician: 'Unassigned',
    estimatedCompletion: '2026-08-11',
    warranty: false,
    photos: [laptopDesk],
    quote: 189,
    timeline: [
      {
        status: 'Received',
        title: 'Claim received',
        description: 'Device logged in at the front counter.',
        date: '2026-08-06',
        time: '9:50 AM',
        done: true,
        current: true,
      },
      {
        status: 'Diagnosing',
        title: 'Diagnosis pending',
        description: 'Will be assigned to a technician today.',
        date: '—',
        time: '',
        done: false,
      },
      {
        status: 'In Repair',
        title: 'In repair',
        description: 'Repair will begin after diagnosis.',
        date: '—',
        time: '',
        done: false,
      },
      {
        status: 'Ready for Pickup',
        title: 'Ready for pickup',
        description: 'We will notify you when ready.',
        date: '—',
        time: '',
        done: false,
      },
    ],
    notes: [],
  },
  {
    id: 'SRV-2026-0469',
    brandId: 'bruno-thailand',
    publicTrackingTokenHash: null,
    publicTrackingCodeHash: null,
    customerName: 'Henry Tanaka',
    customerPhone: '(415) 555-0125',
    customerEmail: 'htanaka@yahoo.com',
    product: 'iPhone 14',
    productCategory: 'Smartphone',
    serialNumber: 'F38QJ1MPLK2W',
    issue: 'Rear camera blurry',
    description: 'Main camera photos are consistently soft. Front camera is fine.',
    status: 'Awaiting Parts',
    priority: 'Normal',
    createdAt: '2026-08-03',
    updatedAt: '2026-08-05',
    closedAt: null,
    technician: 'Daniel Okafor',
    estimatedCompletion: '2026-08-10',
    warranty: false,
    photos: [phoneBroken2],
    quote: 249,
    timeline: [
      {
        status: 'Received',
        title: 'Claim received',
        description: 'Phone logged in for camera fault.',
        date: '2026-08-03',
        time: '1:45 PM',
        done: true,
      },
      {
        status: 'Diagnosing',
        title: 'Diagnosis complete',
        description: 'Camera module needs replacement.',
        date: '2026-08-04',
        time: '10:20 AM',
        done: true,
      },
      {
        status: 'Awaiting Parts',
        title: 'Awaiting parts',
        description: 'Camera module on backorder, ETA 2 business days.',
        date: '2026-08-05',
        time: '3:00 PM',
        done: true,
        current: true,
      },
      {
        status: 'In Repair',
        title: 'In repair',
        description: 'Repair will begin when the part arrives.',
        date: '—',
        time: '',
        done: false,
      },
      {
        status: 'Ready for Pickup',
        title: 'Ready for pickup',
        description: 'We will notify you when ready.',
        date: '—',
        time: '',
        done: false,
      },
    ],
    notes: [],
  },
  {
    id: 'SRV-2026-0465',
    brandId: 'bruno-thailand',
    publicTrackingTokenHash: null,
    publicTrackingCodeHash: null,
    customerName: 'Diane Foster',
    customerPhone: '(415) 555-0198',
    customerEmail: 'dianefoster@icloud.com',
    product: 'MacBook Pro 14" M4',
    productCategory: 'Laptop',
    serialNumber: 'C02ZK4NML9PQ',
    issue: 'Keyboard keys sticky',
    description: 'Space bar and several letter keys are sticky after a coffee spill.',
    status: 'Completed',
    priority: 'High',
    createdAt: '2026-07-22',
    updatedAt: '2026-07-30',
    // Backfilled, not live-generated: this is the one pre-existing seed
    // record already in a terminal status. Derived directly from its own
    // final timeline entry below (date: '2026-07-30', time: '1:10 PM',
    // status: 'Completed') rather than invented — the closest thing this
    // static fixture has to a real "closed" event.
    closedAt: '2026-07-30T13:10:00.000Z',
    technician: 'Priya Nair',
    estimatedCompletion: '2026-07-30',
    warranty: false,
    photos: [laptopMono, laptopDesk],
    quote: 549,
    timeline: [
      {
        status: 'Received',
        title: 'Claim received',
        description: 'Drop-off after liquid exposure.',
        date: '2026-07-22',
        time: '2:30 PM',
        done: true,
      },
      {
        status: 'Diagnosing',
        title: 'Diagnosis complete',
        description: 'Top case with keyboard requires replacement.',
        date: '2026-07-23',
        time: '11:00 AM',
        done: true,
      },
      {
        status: 'In Repair',
        title: 'Repaired',
        description: 'Top case replaced, logic board cleaned and tested.',
        date: '2026-07-28',
        time: '4:15 PM',
        done: true,
      },
      {
        status: 'Quality Check',
        title: 'Passed quality check',
        description: 'All keys responsive, full diagnostics passed.',
        date: '2026-07-29',
        time: '10:00 AM',
        done: true,
      },
      {
        status: 'Completed',
        title: 'Picked up',
        description: 'Device collected by customer. Claim closed.',
        date: '2026-07-30',
        time: '1:10 PM',
        done: true,
        current: true,
      },
    ],
    notes: [],
  },
];

export const technicians = ['Daniel Okafor', 'Priya Nair', 'Unassigned'];

export const productCategories = [
  'Smartphone',
  'Laptop',
  'Tablet',
  'Smartwatch',
  'Headphones',
  'Other',
];
